# Generated by Django 5.2.8 on 2025-11-19 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or description of the product', max_length=200)),
                ('sku', models.CharField(help_text='Unique Product Code (Stock Keeping Unit, barcode)', max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text="Product's selling price", max_digits=10)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current quantity in stock')),
                ('minimum_stock', models.PositiveIntegerField(default=5, help_text='Minimum level for low stock alert')),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, help_text='e.g., 8GB, 16GB', max_length=50)),
                ('storage', models.CharField(blank=True, help_text='e.g., 256GB SSD, 1TB HDD', max_length=100)),
                ('screen_size', models.CharField(blank=True, help_text='e.g., 6.1 inches, 27-inch', max_length=50)),
                ('camera_resolution', models.CharField(blank=True, help_text='e.g., 12MP, 108MP', max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('power_supply', models.CharField(blank=True, help_text='e.g., 127V, 220V, Bivolt', max_length=50)),
                ('connectivity', models.TextField(blank=True, help_text='e.g., Wi-Fi, Bluetooth, Ethernet')),
                ('ports', models.TextField(blank=True, help_text='e.g., USB-C, HDMI, P2')),
                ('build_material', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, help_text='e.g., 1.2kg, 220g', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('movement_date', models.DateTimeField(help_text='Date of the movement, as reported by the user')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (e.g., reason for movement, invoice number)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
